# Generated by Django 4.2.3 on 2023-07-28 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='google_maps',
            new_name='maps',
        ),
        migrations.RenameField(
            model_name='sight',
            old_name='google_maps',
            new_name='maps',
        ),
    ]
