# Generated by Django 4.2.3 on 2023-07-28 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_rename_google_maps_city_maps_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='maps',
            new_name='coordinates',
        ),
        migrations.RenameField(
            model_name='sight',
            old_name='maps',
            new_name='coordinates',
        ),
    ]
