# Generated by Django 4.2.3 on 2023-07-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_rename_maps_city_coordinates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='coordinates',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sight',
            name='coordinates',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='sight',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
