# Generated by Django 4.2.3 on 2023-07-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_city_coordinates_alter_city_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
