# Generated by Django 4.2.3 on 2023-08-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_author_gender_authorsightrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='gender',
            field=models.CharField(choices=[(1, 'Мужчина'), (2, 'Женщина'), (None, 'Не указан')], default=None),
        ),
    ]
