# Generated by Django 4.2.3 on 2023-08-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_author_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='sight',
            name='tourists',
            field=models.ManyToManyField(through='data.AuthorSightRelation', to='data.author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='gender',
            field=models.CharField(choices=[('Мужчина', 'Мужчина'), ('Женщина', 'Женщина'), (None, 'Не указан')], default=None),
        ),
    ]
