# Generated by Django 4.2.3 on 2023-08-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_sight_tourists_alter_author_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorsightrelation',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], null=True),
        ),
    ]
