# Generated by Django 4.2.3 on 2023-08-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_alter_authorsightrelation_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='sight',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=3, null=True),
        ),
    ]
